name: Publish Docker
on:
  push:
    branches:
      - golang

jobs:
  build:
    services:
      mongo:
        image: mvertes/alpine-mongo
        ports:
          - 27017:27017
      firestore:
        image: ridedott/firestore-emulator
        ports:
          - 8080:8080
        env:
          FIRESTORE_PROJECT_ID: project-test
    runs-on: ubuntu-latest
    steps:
      # setup ######################################
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - run: env
      - uses: actions/checkout@v2
      - run: go mod download
      # test #######################################
      - run: make test
      # bump #######################################
      - name: Bump version
        id: bump
        uses: remorses/bump-version@js
        with:
          version_file: VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Unshallow
        run: git fetch --prune --unshallow && git fetch --tags
      # upload binaries ############################
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: --rm-dist --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # cli #######################################
      - run: cd web-ui && yarn --ignore-scripts && yarn build # create web ui assets, also for docker
      - run: cd cli && yarn install --ignore-scripts
      - run: cd cli && yarn test
      - run: cd cli && yarn build
      - run: cd cli && yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
      # docker ####################################
      - name: Publish to Dockerhub
        uses: docker/build-push-action@v1
        with:
          repository: gokedev/goke
          tags: latest,${{ steps.bump.outputs.version }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    # - name: Publish to Gcr.io
    #   uses: elgohr/Publish-Docker-Github-Action@master
    #   with:
    #     name: containerful/goke
    #     registry: gcr.io
    #     username: _json_key
    #     password: ${{ secrets.GCP_KEY_JSON }}
