name: Publish Docker
on:
  push:
    branches:
      - golang

jobs:
  build:
    services:
      mongo:
        image: mvertes/alpine-mongo
        ports:
          - 27017:27017
      firestore:
        image: ridedott/firestore-emulator
        ports:
          - 8080:8080
        env:
          FIRESTORE_PROJECT_ID: project-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - run: env
      - uses: actions/checkout@v2
      - name: Unshallow
        run: git fetch --prune --unshallow
      - run: go mod download
      - run: make test
      - name: Bump version
        id: bump
        uses: remorses/bump-version@js
        with:
          version_file: VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: --rm-dist --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: cd web-ui && yarn && yarn build
      - name: Publish to Dockerhub
        uses: docker/build-push-action@v1
        with:
          repository: gokedev/goke
          tags: latest,${{ steps.bump.outputs.version }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    # - name: Publish to Gcr.io
    #   uses: elgohr/Publish-Docker-Github-Action@master
    #   with:
    #     name: containerful/mongoke
    #     registry: gcr.io
    #     username: _json_key
    #     password: ${{ secrets.GCP_KEY_JSON }}
